### ISSUE TITLE
`nix build` fails

### ISSUE THREAD

**Issue by silky** [marcosh/crem#87] opened 2023-04-13 18:42 UTC
```
       > Test suite crem-doctests: RUNNING...
       > Could not import module: Crem.Example.TwoSwitchesGate. This can be caused by a number of issues:
       >
       >  1. A module found by GHC contained tests, but was not in 'exposed-modules'. If you want
       >     to test non-exposed modules follow the instructions here:
       >     https://github.com/martijnbastiaan/doctest-parallel#test-non-exposed-modules
       >
       >  2. For Cabal users: Cabal did not generate a GHC environment file. Either:
       >    * Run with '--write-ghc-environment-files=always'
       >    * Add 'write-ghc-environment-files: always' to your cabal.project
       >
       >  3. For Cabal users: Cabal did not generate a GHC environment file in time. This
       >     can happen if you use 'cabal test' instead of 'cabal run doctests'. See
       >     https://github.com/martijnbastiaan/doctest-parallel/issues/22.
       >
       >  4. The testsuite executable does not have a dependency on your project library. Please
       >     add it to the 'build-depends' section of the testsuite executable.
       >
       > See the example project at https://github.com/martijnbastiaan/doctest-parallel/blob/main/example/README.md for more information.
       >
       > The original reason given by GHCi was:
       >
       > Error:
       >
       > <no location info>: error:
       >     Could not load module ‘Crem.Example.TwoSwitchesGate’
       >     It is a member of the hidden package ‘crem-0.1.0.0’.
       >     You can run ‘:set -package crem’ to expose it.
       >     (Note: this unloads all the modules in the current scope.)
```

Glancing at the error, it seems like it says that it can't find that module; so I'd guess that `test-suite crem-doctests` is missing `crem-examples`, but that's not the case ... so I'm not sure what's going wrong.

**Comment by silky** [comment] 2023-04-13 18:47
(notably there's no error during `cabal build`, so it's definitely a nix problem.)

**Comment by marcosh** [comment] 2023-04-14 08:31
I guess this is a duplicate of #64.

If that's the case, I tried to solve that issue already without any luck :disappointed:

**Closed** 2023-04-14 09:31 UTC
